name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::274147449864:role/actions-wanko-cc
          aws-region: ap-northeast-1
      - name: zola build
        run: docker run --user $UID:$GID --volume $PWD:/app --workdir /app ghcr.io/getzola/zola:v0.16.0 build
      - run: ls -lR public
      - run: aws s3 sync --delete public/ s3://wanko-cc/
      - run: aws cloudfront create-invalidation --distribution-id E3A3CSEHUOVIZZ --paths '/*'
